export const STATISTICAL_INCOME_REQUEST = 'STATISTICAL_INCOME_REQUEST'
export const STATISTICAL_INCOME_SUCCESS = 'STATISTICAL_INCOME_SUCCESS'
export const STATISTICAL_INCOME_FAIL = 'STATISTICAL_INCOME_FAIL'